name: Build Executable fdp est fait une mise en prod 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # Since it's a Windows application

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name FDP2imgPreview FDP2imgPrevie.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FDP2imgPreview
        path: dist/FDP2imgPreview.exe

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/FDP2imgPreview.exe
        tag_name: v${{ github.run_number }}
        name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}